repos:
  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: black
        language: system
        types: [ python ]

      - id: ruff
        name: Check with ruff
        entry: ruff
        language: system
        pass_filenames: false
        types: [ python ]
        args: [ check, ., --fix ]